from app.models.form_schema import FormField, FieldType, FormDefinition

S0051_FIELDS = [
    # ===================================================================
    # Sektion 0: Kopfdaten / Identifikation
    # ===================================================================
    FormField(
        field_name="PAF_VSNR_trim",
        field_type=FieldType.TEXT,
        label_de="Sozialversicherungsnummer",
        section=0,
        description="Sozialversicherungsnummer der Person, aus deren Versicherung die Leistung beantragt wird",
        extract_from_ai=False,
    ),
    FormField(
        field_name="PAF_AIGR",
        field_type=FieldType.TEXT,
        label_de="Kennzeichen",
        section=0,
        description="Kennzeichen / Aktenzeichen (soweit bekannt)",
        extract_from_ai=False,
    ),
    FormField(
        field_name="DRV_Kopf_PAF_Reha_MSAT_MSNR",
        field_type=FieldType.TEXT,
        label_de="MSAT / MSNR",
        section=0,
        description="Maßnahme-Satz-Nummer / Maßnahme-Nummer",
        extract_from_ai=False,
    ),
    FormField(
        field_name="VERS_NAME",
        field_type=FieldType.TEXT,
        label_de="Name, Vorname (Versicherte/r)",
        section=0,
        description="Name, Vorname der Person, aus deren Versicherung die Leistung beantragt wird",
    ),
    FormField(
        field_name="VERS_GEBDAT",
        field_type=FieldType.TEXT,
        label_de="Geburtsdatum (Versicherte/r)",
        section=0,
        description="Geburtsdatum der versicherten Person (Format: TT.MM.JJJJ)",
    ),
    FormField(
        field_name="PAT_NAME",
        field_type=FieldType.TEXT,
        label_de="Patient/in (Name, Vorname)",
        section=0,
        description="Name, Vorname der Patientin / des Patienten",
    ),
    FormField(
        field_name="PAT_Geburtsdatum",
        field_type=FieldType.TEXT,
        label_de="Geburtsdatum (Patient/in)",
        section=0,
        description="Geburtsdatum der Patientin / des Patienten (Format: TT.MM.JJJJ)",
    ),
    FormField(
        field_name="VERS_STRASSE_HNR",
        field_type=FieldType.TEXT,
        label_de="Straße, Hausnummer",
        section=0,
        description="Straße und Hausnummer des Patienten",
    ),
    FormField(
        field_name="VERS_PLZ",
        field_type=FieldType.TEXT,
        label_de="Postleitzahl",
        section=0,
        description="Postleitzahl des Wohnorts",
    ),
    FormField(
        field_name="VERS_WOHNORT",
        field_type=FieldType.TEXT,
        label_de="Wohnort",
        section=0,
        description="Wohnort des Patienten",
    ),

    # Antragsart-Radio-Buttons (nur eine Auswahl möglich, muss vom User gewählt werden)
    FormField(
        field_name="AW_1",
        field_type=FieldType.RADIO,
        label_de="Leistungen zur medizinischen Rehabilitation",
        section=0,
        description="Antrag auf Leistungen zur medizinischen Rehabilitation",
        radio_group="antragsart",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_2",
        field_type=FieldType.RADIO,
        label_de="Leistungen zur onkologischen Rehabilitation",
        section=0,
        description="Antrag auf Leistungen zur onkologischen Rehabilitation",
        radio_group="antragsart",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_3",
        field_type=FieldType.RADIO,
        label_de="Leistungen zur Teilhabe am Arbeitsleben (LTA)",
        section=0,
        description="Antrag auf Leistungen zur Teilhabe am Arbeitsleben",
        radio_group="antragsart",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_4",
        field_type=FieldType.RADIO,
        label_de="Erwerbsminderungsrente",
        section=0,
        description="Antrag auf Erwerbsminderungsrente",
        radio_group="antragsart",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_5",
        field_type=FieldType.RADIO,
        label_de="Sonstige Leistungen",
        section=0,
        description="Antrag auf sonstige Leistungen",
        radio_group="antragsart",
        extract_from_ai=False,
    ),

    # ===================================================================
    # Sektion 1: Behandlung
    # ===================================================================
    FormField(
        field_name="NAME_DER_ÄRZTIN",
        field_type=FieldType.TEXT,
        label_de="Name der Ärztin (bitte Umlaute!)/des Arztes",
        section=1,
        description="Name der behandelnden Ärztin / des Arztes / Psychotherapeutin / Psychotherapeut",
        extract_from_ai=False,
    ),
    FormField(
        field_name="FACHRICHTUNG",
        field_type=FieldType.TEXT,
        label_de="Fachrichtung",
        section=1,
        description="Medizinische Fachrichtung der behandelnden Ärztin / des Arztes",
        extract_from_ai=False,
    ),
    FormField(
        field_name="VERS_BEHANDLUNG",
        field_type=FieldType.TEXT,
        label_de="In Behandlung seit",
        section=1,
        description="Datum, seit dem sich der Patient in Behandlung befindet (Format: TT.MM.JJJJ)",
    ),
    FormField(
        field_name="VERS_KONTAKT_AM",
        field_type=FieldType.TEXT,
        label_de="Letzter Kontakt am",
        section=1,
        description="Datum des letzten Kontakts mit dem Patienten (Format: TT.MM.JJJJ)",
        extract_from_ai=False,
    ),
    FormField(
        field_name="TELEFONNUMMER_FÜR_RÜCKFRAGEN",
        field_type=FieldType.TEXT,
        label_de="Telefonnummer",
        section=1,
        description="Telefonnummer der Ärztin / des Arztes für Rückfragen",
        extract_from_ai=False,
    ),

    # Kontakthäufigkeit (Radio-Buttons, nur eine Auswahl, User muss wählen)
    FormField(
        field_name="AW_6",
        field_type=FieldType.RADIO,
        label_de="wöchentlich",
        section=1,
        description="Kontakthäufigkeit: wöchentlich",
        radio_group="kontakthaeufigkeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_7",
        field_type=FieldType.RADIO,
        label_de="14-tägig",
        section=1,
        description="Kontakthäufigkeit: 14-tägig / alle zwei Wochen",
        radio_group="kontakthaeufigkeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_8",
        field_type=FieldType.RADIO,
        label_de="monatlich",
        section=1,
        description="Kontakthäufigkeit: monatlich",
        radio_group="kontakthaeufigkeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_9",
        field_type=FieldType.RADIO,
        label_de="seltener",
        section=1,
        description="Kontakthäufigkeit: seltener als monatlich",
        radio_group="kontakthaeufigkeit",
        extract_from_ai=False,
    ),

    # Antrag auf Anregung (Radio-Buttons, nur eine Auswahl, User muss wählen)
    FormField(
        field_name="AW_10",
        field_type=FieldType.RADIO,
        label_de="Antrag nicht auf meine Anregung",
        section=1,
        description="Der Antrag wurde nicht auf Anregung des Arztes gestellt",
        radio_group="anregung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_11",
        field_type=FieldType.RADIO,
        label_de="Antrag auf meine Anregung",
        section=1,
        description="Der Antrag wurde auf Anregung des Arztes gestellt",
        radio_group="anregung",
        extract_from_ai=False,
    ),

    # Sprache
    FormField(
        field_name="VERS_SPRACHE_23_1",
        field_type=FieldType.TEXT,
        label_de="Sprache (falls nicht Deutsch)",
        section=1,
        description="Sprache des Patienten, falls nicht Deutsch",
    ),

    # ===================================================================
    # Sektion 2: Diagnosen
    # ===================================================================
    FormField(
        field_name="VERS_DIAGNOSE_1",
        field_type=FieldType.TEXT,
        label_de="Diagnose 1",
        section=2,
        description="Erste Diagnose (Diagnosetext)",
    ),
    FormField(
        field_name="VERS_DIAGNOSESCH_1",
        field_type=FieldType.TEXT,
        label_de="ICD-10 Code 1",
        section=2,
        description="ICD-10 Diagnoseschlüssel zur ersten Diagnose (z.B. M54.5)",
    ),
    FormField(
        field_name="VERS_DIAGNOSE_2",
        field_type=FieldType.TEXT,
        label_de="Diagnose 2",
        section=2,
        description="Zweite Diagnose (Diagnosetext)",
    ),
    FormField(
        field_name="VERS_DIAGNOSESCH_2",
        field_type=FieldType.TEXT,
        label_de="ICD-10 Code 2",
        section=2,
        description="ICD-10 Diagnoseschlüssel zur zweiten Diagnose",
    ),
    FormField(
        field_name="VERS_DIAGNOSE_3",
        field_type=FieldType.TEXT,
        label_de="Diagnose 3",
        section=2,
        description="Dritte Diagnose (Diagnosetext)",
    ),
    FormField(
        field_name="VERS_DIAGNOSESCH_3",
        field_type=FieldType.TEXT,
        label_de="ICD-10 Code 3",
        section=2,
        description="ICD-10 Diagnoseschlüssel zur dritten Diagnose",
    ),
    FormField(
        field_name="VERS_DIAGNOSE_4",
        field_type=FieldType.TEXT,
        label_de="Diagnose 4",
        section=2,
        description="Vierte Diagnose (Diagnosetext)",
    ),
    FormField(
        field_name="VERS_DIAGNOSESCH_4",
        field_type=FieldType.TEXT,
        label_de="ICD-10 Code 4",
        section=2,
        description="ICD-10 Diagnoseschlüssel zur vierten Diagnose",
    ),

    # ===================================================================
    # Sektion 3: Anamnese
    # ===================================================================
    FormField(
        field_name="ANAMNESE",
        field_type=FieldType.TEXT,
        label_de="Antragsrelevante Anamnese",
        section=3,
        description="Antragsrelevante Anamnese einschließlich Krankenhausaufenthalte und Berichte anderer Fachärzte",
    ),

    # ===================================================================
    # Sektion 4: Funktionseinschraenkungen
    # ===================================================================
    FormField(
        field_name="FUNKTIONSEINSCHRAENKUNGEN",
        field_type=FieldType.TEXT,
        label_de="Funktionseinschränkungen",
        section=4,
        description="Daraus resultierende Funktionseinschränkungen in Beruf und Alltag, was ist krankheitsbedingt nicht mehr möglich",
    ),

    # ===================================================================
    # Sektion 5: Aktivitaeten und Teilhabe (Radio-Button-Matrix)
    # ===================================================================
    # 1. Lernen und Wissensanwendung
    FormField(
        field_name="AW_12",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Lernen und Wissensanwendung: keine Beeinträchtigungen",
        radio_group="aktivitaet_lernen",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_12_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Lernen und Wissensanwendung: Einschränkungen",
        radio_group="aktivitaet_lernen",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_12_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Lernen und Wissensanwendung: Personelle Hilfe nötig",
        radio_group="aktivitaet_lernen",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_12_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Lernen und Wissensanwendung: nicht durchführbar",
        radio_group="aktivitaet_lernen",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_12_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Lernen und Wissensanwendung: Keine Angabe möglich",
        radio_group="aktivitaet_lernen",
        extract_from_ai=False,
    ),

    # 2. Allgemeine Aufgaben und Anforderungen
    FormField(
        field_name="AW_13",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Allgemeine Aufgaben und Anforderungen: keine Beeinträchtigungen",
        radio_group="aktivitaet_aufgaben",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_13_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Allgemeine Aufgaben und Anforderungen: Einschränkungen",
        radio_group="aktivitaet_aufgaben",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_13_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Allgemeine Aufgaben und Anforderungen: Personelle Hilfe nötig",
        radio_group="aktivitaet_aufgaben",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_13_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Allgemeine Aufgaben und Anforderungen: nicht durchführbar",
        radio_group="aktivitaet_aufgaben",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_13_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Allgemeine Aufgaben und Anforderungen: Keine Angabe möglich",
        radio_group="aktivitaet_aufgaben",
        extract_from_ai=False,
    ),

    # 3. Kommunikation
    FormField(
        field_name="AW_14",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Kommunikation: keine Beeinträchtigungen",
        radio_group="aktivitaet_kommunikation",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_14_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Kommunikation: Einschränkungen",
        radio_group="aktivitaet_kommunikation",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_14_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Kommunikation: Personelle Hilfe nötig",
        radio_group="aktivitaet_kommunikation",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_14_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Kommunikation: nicht durchführbar",
        radio_group="aktivitaet_kommunikation",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_14_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Kommunikation: Keine Angabe möglich",
        radio_group="aktivitaet_kommunikation",
        extract_from_ai=False,
    ),

    # 4. Mobilität
    FormField(
        field_name="AW_15",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Mobilität: keine Beeinträchtigungen",
        radio_group="aktivitaet_mobilitaet",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_15_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Mobilität: Einschränkungen",
        radio_group="aktivitaet_mobilitaet",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_15_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Mobilität: Personelle Hilfe nötig",
        radio_group="aktivitaet_mobilitaet",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_15_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Mobilität: nicht durchführbar",
        radio_group="aktivitaet_mobilitaet",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_15_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Mobilität: Keine Angabe möglich",
        radio_group="aktivitaet_mobilitaet",
        extract_from_ai=False,
    ),

    # 5. Selbstversorgung
    FormField(
        field_name="AW_16",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Selbstversorgung: keine Beeinträchtigungen",
        radio_group="aktivitaet_selbstversorgung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_16_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Selbstversorgung: Einschränkungen",
        radio_group="aktivitaet_selbstversorgung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_16_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Selbstversorgung: Personelle Hilfe nötig",
        radio_group="aktivitaet_selbstversorgung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_16_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Selbstversorgung: nicht durchführbar",
        radio_group="aktivitaet_selbstversorgung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_16_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Selbstversorgung: Keine Angabe möglich",
        radio_group="aktivitaet_selbstversorgung",
        extract_from_ai=False,
    ),

    # 6. Häusliches Leben / Haushaltsführung
    FormField(
        field_name="AW_17",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Häusliches Leben / Haushaltsführung: keine Beeinträchtigungen",
        radio_group="aktivitaet_haeusl_leben",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_17_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Häusliches Leben / Haushaltsführung: Einschränkungen",
        radio_group="aktivitaet_haeusl_leben",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_17_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Häusliches Leben / Haushaltsführung: Personelle Hilfe nötig",
        radio_group="aktivitaet_haeusl_leben",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_17_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Häusliches Leben / Haushaltsführung: nicht durchführbar",
        radio_group="aktivitaet_haeusl_leben",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_17_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Häusliches Leben / Haushaltsführung: Keine Angabe möglich",
        radio_group="aktivitaet_haeusl_leben",
        extract_from_ai=False,
    ),

    # 7. Interpersonelle Aktivitäten
    FormField(
        field_name="AW_18",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Interpersonelle Aktivitäten: keine Beeinträchtigungen",
        radio_group="aktivitaet_interpersonell",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_18_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Interpersonelle Aktivitäten: Einschränkungen",
        radio_group="aktivitaet_interpersonell",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_18_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Interpersonelle Aktivitäten: Personelle Hilfe nötig",
        radio_group="aktivitaet_interpersonell",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_18_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Interpersonelle Aktivitäten: nicht durchführbar",
        radio_group="aktivitaet_interpersonell",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_18_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Interpersonelle Aktivitäten: Keine Angabe möglich",
        radio_group="aktivitaet_interpersonell",
        extract_from_ai=False,
    ),

    # 8. Bedeutende Lebensbereiche (Arbeit)
    FormField(
        field_name="AW_19",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Bedeutende Lebensbereiche (Arbeit): keine Beeinträchtigungen",
        radio_group="aktivitaet_arbeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_19_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Bedeutende Lebensbereiche (Arbeit): Einschränkungen",
        radio_group="aktivitaet_arbeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_19_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Bedeutende Lebensbereiche (Arbeit): Personelle Hilfe nötig",
        radio_group="aktivitaet_arbeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_19_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Bedeutende Lebensbereiche (Arbeit): nicht durchführbar",
        radio_group="aktivitaet_arbeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_19_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Bedeutende Lebensbereiche (Arbeit): Keine Angabe möglich",
        radio_group="aktivitaet_arbeit",
        extract_from_ai=False,
    ),

    # 9. Erziehung / Bildung
    FormField(
        field_name="AW_20",
        field_type=FieldType.RADIO,
        label_de="keine Beeinträchtigungen",
        section=5,
        description="Erziehung / Bildung: keine Beeinträchtigungen",
        radio_group="aktivitaet_bildung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_20_1",
        field_type=FieldType.RADIO,
        label_de="Einschränkungen",
        section=5,
        description="Erziehung / Bildung: Einschränkungen",
        radio_group="aktivitaet_bildung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_20_2",
        field_type=FieldType.RADIO,
        label_de="Personelle Hilfe nötig",
        section=5,
        description="Erziehung / Bildung: Personelle Hilfe nötig",
        radio_group="aktivitaet_bildung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_20_3",
        field_type=FieldType.RADIO,
        label_de="nicht durchführbar",
        section=5,
        description="Erziehung / Bildung: nicht durchführbar",
        radio_group="aktivitaet_bildung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_20_4",
        field_type=FieldType.RADIO,
        label_de="Keine Angabe möglich",
        section=5,
        description="Erziehung / Bildung: Keine Angabe möglich",
        radio_group="aktivitaet_bildung",
        extract_from_ai=False,
    ),

    # ===================================================================
    # Sektion 6: Therapie
    # ===================================================================
    FormField(
        field_name="THERAPIE",
        field_type=FieldType.TEXT,
        label_de="Bisherige und aktuelle Therapie",
        section=6,
        description="Bisherige und aktuelle Therapie (Medikamente, Physiotherapie, Psychotherapie etc.)",
    ),

    # ===================================================================
    # Sektion 7: Untersuchungsbefunde
    # ===================================================================
    FormField(
        field_name="UNTERSUCHUNGSBEFUNDE",
        field_type=FieldType.TEXT,
        label_de="Untersuchungsbefunde",
        section=7,
        description="Körperliche und/oder psychische Untersuchungsbefunde",
    ),
    FormField(
        field_name="VERS_KOERPERLAENGE",
        field_type=FieldType.TEXT,
        label_de="Körperlänge (cm)",
        section=7,
        description="Körperlänge / Körpergröße in Zentimetern",
    ),
    FormField(
        field_name="VERS_GEWICHT",
        field_type=FieldType.TEXT,
        label_de="Gewicht (kg)",
        section=7,
        description="Körpergewicht in Kilogramm",
    ),

    # ===================================================================
    # Sektion 8: Medizinisch-technische Befunde
    # ===================================================================
    FormField(
        field_name="MED_TECHN_BEFUNDE",
        field_type=FieldType.TEXT,
        label_de="Medizinisch-technische Befunde",
        section=8,
        description="Medizinisch-technische Befunde (Labor, Roentgen, EKG, etc.)",
    ),

    # ===================================================================
    # Sektion 9: Lebensumstaende
    # ===================================================================
    FormField(
        field_name="LEBENSUMSTAENDE",
        field_type=FieldType.TEXT,
        label_de="Lebensumstände / Kontextfaktoren",
        section=9,
        description="Lebensumstände und Kontextfaktoren (soziales Umfeld, Wohnsituation, berufliche Situation)",
    ),

    # ===================================================================
    # Sektion 10: Risikofaktoren
    # ===================================================================
    FormField(
        field_name="AW_21",
        field_type=FieldType.CHECKBOX,
        label_de="Bewegungsmangel",
        section=10,
        description="Risikofaktor: Bewegungsmangel",
    ),
    FormField(
        field_name="AW_22",
        field_type=FieldType.CHECKBOX,
        label_de="Übergewicht",
        section=10,
        description="Risikofaktor: Übergewicht",
    ),
    FormField(
        field_name="AW_23",
        field_type=FieldType.CHECKBOX,
        label_de="Drogen / Medikamentenmissbrauch",
        section=10,
        description="Risikofaktor: Drogen- oder Medikamentenmissbrauch",
    ),
    FormField(
        field_name="AW_24",
        field_type=FieldType.CHECKBOX,
        label_de="Tabakkonsum",
        section=10,
        description="Risikofaktor: Tabakkonsum / Rauchen",
    ),
    FormField(
        field_name="AW_25",
        field_type=FieldType.CHECKBOX,
        label_de="Alkoholkonsum",
        section=10,
        description="Risikofaktor: erhöhter Alkoholkonsum",
    ),
    FormField(
        field_name="AW_26",
        field_type=FieldType.CHECKBOX,
        label_de="Medikamenteneinnahme",
        section=10,
        description="Risikofaktor: dauerhafte Medikamenteneinnahme",
    ),
    FormField(
        field_name="SONSTIGES",
        field_type=FieldType.CHECKBOX,
        label_de="Sonstiges",
        section=10,
        description="Risikofaktor: Sonstiges",
    ),

    # ===================================================================
    # Sektion 11: Arbeitsunfaehigkeit / Prognose
    # ===================================================================

    # Frage 1: "Die Patientin / der Patient ist derzeit durch mich arbeitsunfähig geschrieben."
    FormField(
        field_name="AW_27",
        field_type=FieldType.RADIO,
        label_de="nein",
        section=11,
        description="Patient ist nicht arbeitsunfähig geschrieben",
        radio_group="arbeitsunfaehig",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_28",
        field_type=FieldType.RADIO,
        label_de="ja",
        section=11,
        description="Patient ist arbeitsunfähig geschrieben",
        radio_group="arbeitsunfaehig",
        extract_from_ai=False,
    ),
    FormField(
        field_name="VERS_AU_SEIT",
        field_type=FieldType.TEXT,
        label_de="seit (Datum)",
        section=11,
        description="Arbeitsunfähig seit (Format: TT.MM.JJJJ)",
        extract_from_ai=False,
        conditional_on="AW_28",
        conditional_value="AW_28",
    ),
    FormField(
        field_name="VERS_AU_GRUND",
        field_type=FieldType.TEXT,
        label_de="wegen",
        section=11,
        description="Grund der Arbeitsunfähigkeit",
        extract_from_ai=False,
        conditional_on="AW_28",
        conditional_value="AW_28",
    ),

    # Frage 2: "Befundänderung in den letzten 12 Monaten"
    FormField(
        field_name="AW_29",
        field_type=FieldType.RADIO,
        label_de="nein",
        section=11,
        description="Keine Befundänderung in den letzten 12 Monaten",
        radio_group="befundaenderung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_30",
        field_type=FieldType.RADIO,
        label_de="ja",
        section=11,
        description="Befundänderung in den letzten 12 Monaten",
        radio_group="befundaenderung",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_31",
        field_type=FieldType.RADIO,
        label_de="Besserung seit",
        section=11,
        description="Befund hat sich gebessert",
        radio_group="befundaenderung_art",
        extract_from_ai=False,
        conditional_on="AW_30",
        conditional_value="AW_30",
    ),
    FormField(
        field_name="VERS_BESSERUNG_DATUM",
        field_type=FieldType.TEXT,
        label_de="Datum Besserung",
        section=11,
        description="Datum, seit dem eine Besserung eingetreten ist (Format: TT.MM.JJJJ)",
        extract_from_ai=False,
        conditional_on="AW_31",
        conditional_value="AW_31",
    ),
    FormField(
        field_name="AW_32",
        field_type=FieldType.RADIO,
        label_de="Verschlechterung seit",
        section=11,
        description="Befund hat sich verschlechtert",
        radio_group="befundaenderung_art",
        extract_from_ai=False,
        conditional_on="AW_30",
        conditional_value="AW_30",
    ),
    FormField(
        field_name="VERS_VERSCHLECHTERUNG_DATUM",
        field_type=FieldType.TEXT,
        label_de="Datum Verschlechterung",
        section=11,
        description="Datum, seit dem eine Verschlechterung eingetreten ist (Format: TT.MM.JJJJ)",
        extract_from_ai=False,
        conditional_on="AW_32",
        conditional_value="AW_32",
    ),

    # Frage 3: "Verständigung ist in deutscher Sprache möglich"
    FormField(
        field_name="AW_33",
        field_type=FieldType.RADIO,
        label_de="nein",
        section=11,
        description="Verständigung in deutscher Sprache nicht möglich",
        radio_group="deutsche_sprache",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_34",
        field_type=FieldType.RADIO,
        label_de="ja",
        section=11,
        description="Verständigung in deutscher Sprache möglich",
        radio_group="deutsche_sprache",
        extract_from_ai=False,
    ),
    FormField(
        field_name="VERS_SPRACHE",
        field_type=FieldType.TEXT,
        label_de="Wenn nein, in welcher Sprache?",
        section=11,
        description="Sprache des Patienten für Verständigung",
        extract_from_ai=False,
        conditional_on="AW_33",
        conditional_value="AW_33",
    ),

    # Frage 4: "Reisefähigkeit für öffentliche Verkehrsmittel besteht."
    FormField(
        field_name="AW_35",
        field_type=FieldType.RADIO,
        label_de="nein",
        section=11,
        description="Reisefähigkeit für öffentliche Verkehrsmittel besteht nicht",
        radio_group="reisefaehigkeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_36",
        field_type=FieldType.RADIO,
        label_de="ja",
        section=11,
        description="Reisefähigkeit für öffentliche Verkehrsmittel besteht",
        radio_group="reisefaehigkeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_37",
        field_type=FieldType.CHECKBOX,
        label_de="mit Begleitung",
        section=11,
        description="Reisefähigkeit nur mit Begleitung",
        extract_from_ai=False,
        conditional_on="AW_36",
        conditional_value="AW_36",
    ),

    # Frage 5: "Besserung der Leistungsfähigkeit ist möglich."
    FormField(
        field_name="AW_38",
        field_type=FieldType.RADIO,
        label_de="nein",
        section=11,
        description="Besserung der Leistungsfähigkeit ist nicht möglich",
        radio_group="besserung_leistungsfaehigkeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_39",
        field_type=FieldType.RADIO,
        label_de="ja",
        section=11,
        description="Besserung der Leistungsfähigkeit ist möglich",
        radio_group="besserung_leistungsfaehigkeit",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_40",
        field_type=FieldType.RADIO,
        label_de="kann ich nicht beurteilen",
        section=11,
        description="Besserung der Leistungsfähigkeit kann nicht beurteilt werden",
        radio_group="besserung_leistungsfaehigkeit",
        extract_from_ai=False,
    ),

    # Frage 6: "Belastbarkeit für eine Rehabilitation besteht."
    FormField(
        field_name="AW_41",
        field_type=FieldType.RADIO,
        label_de="nein",
        section=11,
        description="Belastbarkeit für eine Rehabilitation besteht nicht",
        radio_group="belastbarkeit_reha",
        extract_from_ai=False,
    ),
    FormField(
        field_name="AW_42",
        field_type=FieldType.RADIO,
        label_de="ja",
        section=11,
        description="Belastbarkeit für eine Rehabilitation besteht",
        radio_group="belastbarkeit_reha",
        extract_from_ai=False,
    ),

    # ===================================================================
    # Sektion 12: Bemerkungen
    # ===================================================================
    FormField(
        field_name="BEMERKUNGEN",
        field_type=FieldType.TEXT,
        label_de="Bemerkungen",
        section=12,
        description="Ergänzende Bemerkungen und Anmerkungen",
    ),
]

S0051_DEFINITION = FormDefinition(
    form_id="S0051",
    form_title="Befundbericht fuer die Deutsche Rentenversicherung",
    fields=S0051_FIELDS,
)
